// ORACLE 2일차_1


SHOW USER;

// TABLE 생성
CREATE TABLE USER_NO_CONSTRAINT (
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),           // 한글로 몇 글자? 6글자
    USER_PWD VARCHAR2(30),
    USER_NAME VARCHAR2(30),         // 한글로 10글자(한글자에 3바이트라서)
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
    );
    
SELECT * FROM USER_NO_CONSTRAINT;
DESC USER_NO_CONSTRAINT;


// NOT_NULL 제약조건 테이블
CREATE TABLE USER_CONSTRAINT (
    USER_NO NUMBER,
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
    );

// UNIQUE 제약조건 테이블
CREATE TABLE USER_CONSTRAINT_UNIQUE (
    USER_NO NUMBER,
    USER_ID VARCHAR2(20) UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
    );

// PRIMARY 제약조건 테이블
CREATE TABLE USER_PRIMARY_KEY (
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) PRIMARY KEY, // UNIQUE + NOT_NULL
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
    );

// CHECK 제약조건 테이블
CREATE TABLE USER_CHECK (
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) CONSTRAINT PK_USER_ID PRIMARY KEY,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN ('M', 'F')),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
    );

// DEFAULT 제약조건 테이블
CREATE TABLE USER_DEFAULT (
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(20) CONSTRAINT PK_USER_ID PRIMARY KEY,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN ('M', 'F')),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50),
    USER_DATE DATE DEFAULT SYSDATE
    );

INSERT INTO USER_DEFAULT VALUES (
    1, 'khuser01', 'pass01', '일용자', 'M', '01012345678', 'khuser01@kh.or.kr'
    , '23/12/07'
    );
INSERT INTO USER_DEFAULT VALUES (
    2, 'khuser02', 'pass02', '이용자', 'M', '01012345678', 'khuser02@kh.or.kr'
    , '23/12/14'
    );
INSERT INTO USER_DEFAULT VALUES (
    3, 'khuser03', 'pass03', '삼용자', 'M', '01012345678', 'khuser03@kh.or.kr'
    , SYSDATE
    );
INSERT INTO USER_DEFAULT VALUES (
    4, 'khuser04', 'pass04', '사용자', 'M', '01012345678', 'khuser04@kh.or.kr'
    , DEFAULT
    );

    
--DEFAULT 제약조건을 기본값을 설정할 때 사용하고 default를 쓰면 다른 것을 신경쓰지 않고
--데이터를 넣을 수 있음!
--SYSDATE 사용하면 오늘 날짜 23/12/07 들어가는 것 확인! SYSDATE 날짜함수라고 함.
--오늘 날짜를 입력해주는 역할을 함!


-----------------------------------------------
                    COMMIT;
-----------------------------------------------